image: docker:latest

services:
  - docker:dind

stages:
- build
- test

sast-semgrep-app:
  stage: test
  image: returntocorp/semgrep
  script:
    - echo $SEMGREP_APP_TOKEN
    - echo $PAT
    - semgrep ci
  rules:
    # Scan changed files in MRs, (diff-aware scanning):
    - if: $CI_MERGE_REQUEST_IID
    # Scan mainline (default) branches and report all findings.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    # Upload findings to GitLab SAST Dashboard:
    SEMGREP_GITLAB_JSON: "1"
    SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
    GITLAB_TOKEN: $PAT
